[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer']
aptPkgs = ['libzip-dev', 'libicu-dev']

[phases.install]
cmds = ['docker-php-ext-install intl zip pdo pdo_mysql']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'npm ci',
    'npm run build'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
